// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PTarget.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PTarget_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PTarget_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PTarget_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PTarget_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PTarget_2eproto;
class PCoordinate;
class PCoordinateDefaultTypeInternal;
extern PCoordinateDefaultTypeInternal _PCoordinate_default_instance_;
class PIndexPoint;
class PIndexPointDefaultTypeInternal;
extern PIndexPointDefaultTypeInternal _PIndexPoint_default_instance_;
class PIndexPointArray;
class PIndexPointArrayDefaultTypeInternal;
extern PIndexPointArrayDefaultTypeInternal _PIndexPointArray_default_instance_;
class PMat;
class PMatDefaultTypeInternal;
extern PMatDefaultTypeInternal _PMat_default_instance_;
class PTarget;
class PTargetDefaultTypeInternal;
extern PTargetDefaultTypeInternal _PTarget_default_instance_;
class PTargetArray;
class PTargetArrayDefaultTypeInternal;
extern PTargetArrayDefaultTypeInternal _PTargetArray_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PCoordinate* Arena::CreateMaybeMessage<::PCoordinate>(Arena*);
template<> ::PIndexPoint* Arena::CreateMaybeMessage<::PIndexPoint>(Arena*);
template<> ::PIndexPointArray* Arena::CreateMaybeMessage<::PIndexPointArray>(Arena*);
template<> ::PMat* Arena::CreateMaybeMessage<::PMat>(Arena*);
template<> ::PTarget* Arena::CreateMaybeMessage<::PTarget>(Arena*);
template<> ::PTargetArray* Arena::CreateMaybeMessage<::PTargetArray>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PMat PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PMat) */ {
 public:
  inline PMat() : PMat(nullptr) {};
  virtual ~PMat();

  PMat(const PMat& from);
  PMat(PMat&& from) noexcept
    : PMat() {
    *this = ::std::move(from);
  }

  inline PMat& operator=(const PMat& from) {
    CopyFrom(from);
    return *this;
  }
  inline PMat& operator=(PMat&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PMat& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PMat* internal_default_instance() {
    return reinterpret_cast<const PMat*>(
               &_PMat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PMat& a, PMat& b) {
    a.Swap(&b);
  }
  inline void Swap(PMat* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PMat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PMat* New() const final {
    return CreateMaybeMessage<PMat>(nullptr);
  }

  PMat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PMat>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PMat& from);
  void MergeFrom(const PMat& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PMat* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PMat";
  }
  protected:
  explicit PMat(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PTarget_2eproto);
    return ::descriptor_table_PTarget_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
    kSizeFieldNumber = 2,
    kColsFieldNumber = 3,
    kRowsFieldNumber = 4,
  };
  // bytes data = 1;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_data(
      std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int64 size = 2;
  void clear_size();
  ::PROTOBUF_NAMESPACE_ID::int64 size() const;
  void set_size(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_size() const;
  void _internal_set_size(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 cols = 3;
  void clear_cols();
  ::PROTOBUF_NAMESPACE_ID::int32 cols() const;
  void set_cols(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_cols() const;
  void _internal_set_cols(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 rows = 4;
  void clear_rows();
  ::PROTOBUF_NAMESPACE_ID::int32 rows() const;
  void set_rows(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_rows() const;
  void _internal_set_rows(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:PMat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::PROTOBUF_NAMESPACE_ID::int64 size_;
  ::PROTOBUF_NAMESPACE_ID::int32 cols_;
  ::PROTOBUF_NAMESPACE_ID::int32 rows_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PTarget_2eproto;
};
// -------------------------------------------------------------------

class PCoordinate PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PCoordinate) */ {
 public:
  inline PCoordinate() : PCoordinate(nullptr) {};
  virtual ~PCoordinate();

  PCoordinate(const PCoordinate& from);
  PCoordinate(PCoordinate&& from) noexcept
    : PCoordinate() {
    *this = ::std::move(from);
  }

  inline PCoordinate& operator=(const PCoordinate& from) {
    CopyFrom(from);
    return *this;
  }
  inline PCoordinate& operator=(PCoordinate&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PCoordinate& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PCoordinate* internal_default_instance() {
    return reinterpret_cast<const PCoordinate*>(
               &_PCoordinate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PCoordinate& a, PCoordinate& b) {
    a.Swap(&b);
  }
  inline void Swap(PCoordinate* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PCoordinate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PCoordinate* New() const final {
    return CreateMaybeMessage<PCoordinate>(nullptr);
  }

  PCoordinate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PCoordinate>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PCoordinate& from);
  void MergeFrom(const PCoordinate& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PCoordinate* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PCoordinate";
  }
  protected:
  explicit PCoordinate(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PTarget_2eproto);
    return ::descriptor_table_PTarget_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:PCoordinate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PTarget_2eproto;
};
// -------------------------------------------------------------------

class PTarget PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PTarget) */ {
 public:
  inline PTarget() : PTarget(nullptr) {};
  virtual ~PTarget();

  PTarget(const PTarget& from);
  PTarget(PTarget&& from) noexcept
    : PTarget() {
    *this = ::std::move(from);
  }

  inline PTarget& operator=(const PTarget& from) {
    CopyFrom(from);
    return *this;
  }
  inline PTarget& operator=(PTarget&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PTarget& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PTarget* internal_default_instance() {
    return reinterpret_cast<const PTarget*>(
               &_PTarget_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PTarget& a, PTarget& b) {
    a.Swap(&b);
  }
  inline void Swap(PTarget* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PTarget* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PTarget* New() const final {
    return CreateMaybeMessage<PTarget>(nullptr);
  }

  PTarget* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PTarget>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PTarget& from);
  void MergeFrom(const PTarget& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PTarget* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PTarget";
  }
  protected:
  explicit PTarget(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PTarget_2eproto);
    return ::descriptor_table_PTarget_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUuidFieldNumber = 1,
    kTypeFieldNumber = 2,
    kImageFieldNumber = 3,
    kPositionFieldNumber = 4,
    kTimeStampFieldNumber = 5,
  };
  // string uuid = 1;
  void clear_uuid();
  const std::string& uuid() const;
  void set_uuid(const std::string& value);
  void set_uuid(std::string&& value);
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  std::string* mutable_uuid();
  std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_uuid();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_uuid(
      std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // string type = 2;
  void clear_type();
  const std::string& type() const;
  void set_type(const std::string& value);
  void set_type(std::string&& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  std::string* mutable_type();
  std::string* release_type();
  void set_allocated_type(std::string* type);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_type();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_type(
      std::string* type);
  private:
  const std::string& _internal_type() const;
  void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // .PMat image = 3;
  bool has_image() const;
  private:
  bool _internal_has_image() const;
  public:
  void clear_image();
  const ::PMat& image() const;
  ::PMat* release_image();
  ::PMat* mutable_image();
  void set_allocated_image(::PMat* image);
  private:
  const ::PMat& _internal_image() const;
  ::PMat* _internal_mutable_image();
  public:
  void unsafe_arena_set_allocated_image(
      ::PMat* image);
  ::PMat* unsafe_arena_release_image();

  // .PCoordinate position = 4;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::PCoordinate& position() const;
  ::PCoordinate* release_position();
  ::PCoordinate* mutable_position();
  void set_allocated_position(::PCoordinate* position);
  private:
  const ::PCoordinate& _internal_position() const;
  ::PCoordinate* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::PCoordinate* position);
  ::PCoordinate* unsafe_arena_release_position();

  // int64 time_stamp = 5;
  void clear_time_stamp();
  ::PROTOBUF_NAMESPACE_ID::int64 time_stamp() const;
  void set_time_stamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_time_stamp() const;
  void _internal_set_time_stamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:PTarget)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
  ::PMat* image_;
  ::PCoordinate* position_;
  ::PROTOBUF_NAMESPACE_ID::int64 time_stamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PTarget_2eproto;
};
// -------------------------------------------------------------------

class PTargetArray PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PTargetArray) */ {
 public:
  inline PTargetArray() : PTargetArray(nullptr) {};
  virtual ~PTargetArray();

  PTargetArray(const PTargetArray& from);
  PTargetArray(PTargetArray&& from) noexcept
    : PTargetArray() {
    *this = ::std::move(from);
  }

  inline PTargetArray& operator=(const PTargetArray& from) {
    CopyFrom(from);
    return *this;
  }
  inline PTargetArray& operator=(PTargetArray&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PTargetArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PTargetArray* internal_default_instance() {
    return reinterpret_cast<const PTargetArray*>(
               &_PTargetArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PTargetArray& a, PTargetArray& b) {
    a.Swap(&b);
  }
  inline void Swap(PTargetArray* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PTargetArray* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PTargetArray* New() const final {
    return CreateMaybeMessage<PTargetArray>(nullptr);
  }

  PTargetArray* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PTargetArray>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PTargetArray& from);
  void MergeFrom(const PTargetArray& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PTargetArray* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PTargetArray";
  }
  protected:
  explicit PTargetArray(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PTarget_2eproto);
    return ::descriptor_table_PTarget_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetsFieldNumber = 5,
    kUuidFieldNumber = 1,
    kTypeFieldNumber = 2,
    kLatestPositionFieldNumber = 3,
    kUpdateTimeFieldNumber = 4,
  };
  // repeated .PTarget targets = 5;
  int targets_size() const;
  private:
  int _internal_targets_size() const;
  public:
  void clear_targets();
  ::PTarget* mutable_targets(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PTarget >*
      mutable_targets();
  private:
  const ::PTarget& _internal_targets(int index) const;
  ::PTarget* _internal_add_targets();
  public:
  const ::PTarget& targets(int index) const;
  ::PTarget* add_targets();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PTarget >&
      targets() const;

  // string uuid = 1;
  void clear_uuid();
  const std::string& uuid() const;
  void set_uuid(const std::string& value);
  void set_uuid(std::string&& value);
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  std::string* mutable_uuid();
  std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_uuid();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_uuid(
      std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // string type = 2;
  void clear_type();
  const std::string& type() const;
  void set_type(const std::string& value);
  void set_type(std::string&& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  std::string* mutable_type();
  std::string* release_type();
  void set_allocated_type(std::string* type);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_type();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_type(
      std::string* type);
  private:
  const std::string& _internal_type() const;
  void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // .PCoordinate latest_position = 3;
  bool has_latest_position() const;
  private:
  bool _internal_has_latest_position() const;
  public:
  void clear_latest_position();
  const ::PCoordinate& latest_position() const;
  ::PCoordinate* release_latest_position();
  ::PCoordinate* mutable_latest_position();
  void set_allocated_latest_position(::PCoordinate* latest_position);
  private:
  const ::PCoordinate& _internal_latest_position() const;
  ::PCoordinate* _internal_mutable_latest_position();
  public:
  void unsafe_arena_set_allocated_latest_position(
      ::PCoordinate* latest_position);
  ::PCoordinate* unsafe_arena_release_latest_position();

  // int64 update_time = 4;
  void clear_update_time();
  ::PROTOBUF_NAMESPACE_ID::int64 update_time() const;
  void set_update_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_update_time() const;
  void _internal_set_update_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:PTargetArray)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PTarget > targets_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
  ::PCoordinate* latest_position_;
  ::PROTOBUF_NAMESPACE_ID::int64 update_time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PTarget_2eproto;
};
// -------------------------------------------------------------------

class PIndexPoint PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PIndexPoint) */ {
 public:
  inline PIndexPoint() : PIndexPoint(nullptr) {};
  virtual ~PIndexPoint();

  PIndexPoint(const PIndexPoint& from);
  PIndexPoint(PIndexPoint&& from) noexcept
    : PIndexPoint() {
    *this = ::std::move(from);
  }

  inline PIndexPoint& operator=(const PIndexPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline PIndexPoint& operator=(PIndexPoint&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PIndexPoint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PIndexPoint* internal_default_instance() {
    return reinterpret_cast<const PIndexPoint*>(
               &_PIndexPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PIndexPoint& a, PIndexPoint& b) {
    a.Swap(&b);
  }
  inline void Swap(PIndexPoint* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PIndexPoint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PIndexPoint* New() const final {
    return CreateMaybeMessage<PIndexPoint>(nullptr);
  }

  PIndexPoint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PIndexPoint>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PIndexPoint& from);
  void MergeFrom(const PIndexPoint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PIndexPoint* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PIndexPoint";
  }
  protected:
  explicit PIndexPoint(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PTarget_2eproto);
    return ::descriptor_table_PTarget_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUuidFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kZFieldNumber = 4,
  };
  // string uuid = 1;
  void clear_uuid();
  const std::string& uuid() const;
  void set_uuid(const std::string& value);
  void set_uuid(std::string&& value);
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  std::string* mutable_uuid();
  std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_uuid();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_uuid(
      std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // float x = 2;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 3;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 4;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:PIndexPoint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PTarget_2eproto;
};
// -------------------------------------------------------------------

class PIndexPointArray PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PIndexPointArray) */ {
 public:
  inline PIndexPointArray() : PIndexPointArray(nullptr) {};
  virtual ~PIndexPointArray();

  PIndexPointArray(const PIndexPointArray& from);
  PIndexPointArray(PIndexPointArray&& from) noexcept
    : PIndexPointArray() {
    *this = ::std::move(from);
  }

  inline PIndexPointArray& operator=(const PIndexPointArray& from) {
    CopyFrom(from);
    return *this;
  }
  inline PIndexPointArray& operator=(PIndexPointArray&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PIndexPointArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PIndexPointArray* internal_default_instance() {
    return reinterpret_cast<const PIndexPointArray*>(
               &_PIndexPointArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(PIndexPointArray& a, PIndexPointArray& b) {
    a.Swap(&b);
  }
  inline void Swap(PIndexPointArray* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PIndexPointArray* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PIndexPointArray* New() const final {
    return CreateMaybeMessage<PIndexPointArray>(nullptr);
  }

  PIndexPointArray* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PIndexPointArray>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PIndexPointArray& from);
  void MergeFrom(const PIndexPointArray& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PIndexPointArray* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PIndexPointArray";
  }
  protected:
  explicit PIndexPointArray(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PTarget_2eproto);
    return ::descriptor_table_PTarget_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointsFieldNumber = 1,
  };
  // repeated .PIndexPoint points = 1;
  int points_size() const;
  private:
  int _internal_points_size() const;
  public:
  void clear_points();
  ::PIndexPoint* mutable_points(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PIndexPoint >*
      mutable_points();
  private:
  const ::PIndexPoint& _internal_points(int index) const;
  ::PIndexPoint* _internal_add_points();
  public:
  const ::PIndexPoint& points(int index) const;
  ::PIndexPoint* add_points();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PIndexPoint >&
      points() const;

  // @@protoc_insertion_point(class_scope:PIndexPointArray)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PIndexPoint > points_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PTarget_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PMat

// bytes data = 1;
inline void PMat::clear_data() {
  data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PMat::data() const {
  // @@protoc_insertion_point(field_get:PMat.data)
  return _internal_data();
}
inline void PMat::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:PMat.data)
}
inline std::string* PMat::mutable_data() {
  // @@protoc_insertion_point(field_mutable:PMat.data)
  return _internal_mutable_data();
}
inline const std::string& PMat::_internal_data() const {
  return data_.Get();
}
inline void PMat::_internal_set_data(const std::string& value) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PMat::set_data(std::string&& value) {
  
  data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PMat.data)
}
inline void PMat::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PMat.data)
}
inline void PMat::set_data(const void* value,
    size_t size) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PMat.data)
}
inline std::string* PMat::_internal_mutable_data() {
  
  return data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PMat::release_data() {
  // @@protoc_insertion_point(field_release:PMat.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PMat::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PMat.data)
}
inline std::string* PMat::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PMat.data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PMat::unsafe_arena_set_allocated_data(
    std::string* data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (data != nullptr) {
    
  } else {
    
  }
  data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PMat.data)
}

// int64 size = 2;
inline void PMat::clear_size() {
  size_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PMat::_internal_size() const {
  return size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PMat::size() const {
  // @@protoc_insertion_point(field_get:PMat.size)
  return _internal_size();
}
inline void PMat::_internal_set_size(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  size_ = value;
}
inline void PMat::set_size(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:PMat.size)
}

// int32 cols = 3;
inline void PMat::clear_cols() {
  cols_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PMat::_internal_cols() const {
  return cols_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PMat::cols() const {
  // @@protoc_insertion_point(field_get:PMat.cols)
  return _internal_cols();
}
inline void PMat::_internal_set_cols(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  cols_ = value;
}
inline void PMat::set_cols(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_cols(value);
  // @@protoc_insertion_point(field_set:PMat.cols)
}

// int32 rows = 4;
inline void PMat::clear_rows() {
  rows_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PMat::_internal_rows() const {
  return rows_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PMat::rows() const {
  // @@protoc_insertion_point(field_get:PMat.rows)
  return _internal_rows();
}
inline void PMat::_internal_set_rows(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  rows_ = value;
}
inline void PMat::set_rows(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_rows(value);
  // @@protoc_insertion_point(field_set:PMat.rows)
}

// -------------------------------------------------------------------

// PCoordinate

// float x = 1;
inline void PCoordinate::clear_x() {
  x_ = 0;
}
inline float PCoordinate::_internal_x() const {
  return x_;
}
inline float PCoordinate::x() const {
  // @@protoc_insertion_point(field_get:PCoordinate.x)
  return _internal_x();
}
inline void PCoordinate::_internal_set_x(float value) {
  
  x_ = value;
}
inline void PCoordinate::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:PCoordinate.x)
}

// float y = 2;
inline void PCoordinate::clear_y() {
  y_ = 0;
}
inline float PCoordinate::_internal_y() const {
  return y_;
}
inline float PCoordinate::y() const {
  // @@protoc_insertion_point(field_get:PCoordinate.y)
  return _internal_y();
}
inline void PCoordinate::_internal_set_y(float value) {
  
  y_ = value;
}
inline void PCoordinate::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:PCoordinate.y)
}

// float z = 3;
inline void PCoordinate::clear_z() {
  z_ = 0;
}
inline float PCoordinate::_internal_z() const {
  return z_;
}
inline float PCoordinate::z() const {
  // @@protoc_insertion_point(field_get:PCoordinate.z)
  return _internal_z();
}
inline void PCoordinate::_internal_set_z(float value) {
  
  z_ = value;
}
inline void PCoordinate::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:PCoordinate.z)
}

// -------------------------------------------------------------------

// PTarget

// string uuid = 1;
inline void PTarget::clear_uuid() {
  uuid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PTarget::uuid() const {
  // @@protoc_insertion_point(field_get:PTarget.uuid)
  return _internal_uuid();
}
inline void PTarget::set_uuid(const std::string& value) {
  _internal_set_uuid(value);
  // @@protoc_insertion_point(field_set:PTarget.uuid)
}
inline std::string* PTarget::mutable_uuid() {
  // @@protoc_insertion_point(field_mutable:PTarget.uuid)
  return _internal_mutable_uuid();
}
inline const std::string& PTarget::_internal_uuid() const {
  return uuid_.Get();
}
inline void PTarget::_internal_set_uuid(const std::string& value) {
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PTarget::set_uuid(std::string&& value) {
  
  uuid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PTarget.uuid)
}
inline void PTarget::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PTarget.uuid)
}
inline void PTarget::set_uuid(const char* value,
    size_t size) {
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PTarget.uuid)
}
inline std::string* PTarget::_internal_mutable_uuid() {
  
  return uuid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PTarget::release_uuid() {
  // @@protoc_insertion_point(field_release:PTarget.uuid)
  return uuid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PTarget::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  uuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uuid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PTarget.uuid)
}
inline std::string* PTarget::unsafe_arena_release_uuid() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PTarget.uuid)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return uuid_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PTarget::unsafe_arena_set_allocated_uuid(
    std::string* uuid) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (uuid != nullptr) {
    
  } else {
    
  }
  uuid_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      uuid, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PTarget.uuid)
}

// string type = 2;
inline void PTarget::clear_type() {
  type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PTarget::type() const {
  // @@protoc_insertion_point(field_get:PTarget.type)
  return _internal_type();
}
inline void PTarget::set_type(const std::string& value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:PTarget.type)
}
inline std::string* PTarget::mutable_type() {
  // @@protoc_insertion_point(field_mutable:PTarget.type)
  return _internal_mutable_type();
}
inline const std::string& PTarget::_internal_type() const {
  return type_.Get();
}
inline void PTarget::_internal_set_type(const std::string& value) {
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PTarget::set_type(std::string&& value) {
  
  type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PTarget.type)
}
inline void PTarget::set_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PTarget.type)
}
inline void PTarget::set_type(const char* value,
    size_t size) {
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PTarget.type)
}
inline std::string* PTarget::_internal_mutable_type() {
  
  return type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PTarget::release_type() {
  // @@protoc_insertion_point(field_release:PTarget.type)
  return type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PTarget::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    
  } else {
    
  }
  type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PTarget.type)
}
inline std::string* PTarget::unsafe_arena_release_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PTarget.type)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return type_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PTarget::unsafe_arena_set_allocated_type(
    std::string* type) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (type != nullptr) {
    
  } else {
    
  }
  type_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      type, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PTarget.type)
}

// .PMat image = 3;
inline bool PTarget::_internal_has_image() const {
  return this != internal_default_instance() && image_ != nullptr;
}
inline bool PTarget::has_image() const {
  return _internal_has_image();
}
inline void PTarget::clear_image() {
  if (GetArena() == nullptr && image_ != nullptr) {
    delete image_;
  }
  image_ = nullptr;
}
inline const ::PMat& PTarget::_internal_image() const {
  const ::PMat* p = image_;
  return p != nullptr ? *p : *reinterpret_cast<const ::PMat*>(
      &::_PMat_default_instance_);
}
inline const ::PMat& PTarget::image() const {
  // @@protoc_insertion_point(field_get:PTarget.image)
  return _internal_image();
}
inline void PTarget::unsafe_arena_set_allocated_image(
    ::PMat* image) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(image_);
  }
  image_ = image;
  if (image) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PTarget.image)
}
inline ::PMat* PTarget::release_image() {
  auto temp = unsafe_arena_release_image();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::PMat* PTarget::unsafe_arena_release_image() {
  // @@protoc_insertion_point(field_release:PTarget.image)
  
  ::PMat* temp = image_;
  image_ = nullptr;
  return temp;
}
inline ::PMat* PTarget::_internal_mutable_image() {
  
  if (image_ == nullptr) {
    auto* p = CreateMaybeMessage<::PMat>(GetArena());
    image_ = p;
  }
  return image_;
}
inline ::PMat* PTarget::mutable_image() {
  // @@protoc_insertion_point(field_mutable:PTarget.image)
  return _internal_mutable_image();
}
inline void PTarget::set_allocated_image(::PMat* image) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete image_;
  }
  if (image) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(image);
    if (message_arena != submessage_arena) {
      image = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, image, submessage_arena);
    }
    
  } else {
    
  }
  image_ = image;
  // @@protoc_insertion_point(field_set_allocated:PTarget.image)
}

// .PCoordinate position = 4;
inline bool PTarget::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool PTarget::has_position() const {
  return _internal_has_position();
}
inline void PTarget::clear_position() {
  if (GetArena() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::PCoordinate& PTarget::_internal_position() const {
  const ::PCoordinate* p = position_;
  return p != nullptr ? *p : *reinterpret_cast<const ::PCoordinate*>(
      &::_PCoordinate_default_instance_);
}
inline const ::PCoordinate& PTarget::position() const {
  // @@protoc_insertion_point(field_get:PTarget.position)
  return _internal_position();
}
inline void PTarget::unsafe_arena_set_allocated_position(
    ::PCoordinate* position) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PTarget.position)
}
inline ::PCoordinate* PTarget::release_position() {
  auto temp = unsafe_arena_release_position();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::PCoordinate* PTarget::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:PTarget.position)
  
  ::PCoordinate* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::PCoordinate* PTarget::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::PCoordinate>(GetArena());
    position_ = p;
  }
  return position_;
}
inline ::PCoordinate* PTarget::mutable_position() {
  // @@protoc_insertion_point(field_mutable:PTarget.position)
  return _internal_mutable_position();
}
inline void PTarget::set_allocated_position(::PCoordinate* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:PTarget.position)
}

// int64 time_stamp = 5;
inline void PTarget::clear_time_stamp() {
  time_stamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PTarget::_internal_time_stamp() const {
  return time_stamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PTarget::time_stamp() const {
  // @@protoc_insertion_point(field_get:PTarget.time_stamp)
  return _internal_time_stamp();
}
inline void PTarget::_internal_set_time_stamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  time_stamp_ = value;
}
inline void PTarget::set_time_stamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_time_stamp(value);
  // @@protoc_insertion_point(field_set:PTarget.time_stamp)
}

// -------------------------------------------------------------------

// PTargetArray

// string uuid = 1;
inline void PTargetArray::clear_uuid() {
  uuid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PTargetArray::uuid() const {
  // @@protoc_insertion_point(field_get:PTargetArray.uuid)
  return _internal_uuid();
}
inline void PTargetArray::set_uuid(const std::string& value) {
  _internal_set_uuid(value);
  // @@protoc_insertion_point(field_set:PTargetArray.uuid)
}
inline std::string* PTargetArray::mutable_uuid() {
  // @@protoc_insertion_point(field_mutable:PTargetArray.uuid)
  return _internal_mutable_uuid();
}
inline const std::string& PTargetArray::_internal_uuid() const {
  return uuid_.Get();
}
inline void PTargetArray::_internal_set_uuid(const std::string& value) {
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PTargetArray::set_uuid(std::string&& value) {
  
  uuid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PTargetArray.uuid)
}
inline void PTargetArray::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PTargetArray.uuid)
}
inline void PTargetArray::set_uuid(const char* value,
    size_t size) {
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PTargetArray.uuid)
}
inline std::string* PTargetArray::_internal_mutable_uuid() {
  
  return uuid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PTargetArray::release_uuid() {
  // @@protoc_insertion_point(field_release:PTargetArray.uuid)
  return uuid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PTargetArray::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  uuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uuid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PTargetArray.uuid)
}
inline std::string* PTargetArray::unsafe_arena_release_uuid() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PTargetArray.uuid)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return uuid_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PTargetArray::unsafe_arena_set_allocated_uuid(
    std::string* uuid) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (uuid != nullptr) {
    
  } else {
    
  }
  uuid_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      uuid, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PTargetArray.uuid)
}

// string type = 2;
inline void PTargetArray::clear_type() {
  type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PTargetArray::type() const {
  // @@protoc_insertion_point(field_get:PTargetArray.type)
  return _internal_type();
}
inline void PTargetArray::set_type(const std::string& value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:PTargetArray.type)
}
inline std::string* PTargetArray::mutable_type() {
  // @@protoc_insertion_point(field_mutable:PTargetArray.type)
  return _internal_mutable_type();
}
inline const std::string& PTargetArray::_internal_type() const {
  return type_.Get();
}
inline void PTargetArray::_internal_set_type(const std::string& value) {
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PTargetArray::set_type(std::string&& value) {
  
  type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PTargetArray.type)
}
inline void PTargetArray::set_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PTargetArray.type)
}
inline void PTargetArray::set_type(const char* value,
    size_t size) {
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PTargetArray.type)
}
inline std::string* PTargetArray::_internal_mutable_type() {
  
  return type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PTargetArray::release_type() {
  // @@protoc_insertion_point(field_release:PTargetArray.type)
  return type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PTargetArray::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    
  } else {
    
  }
  type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PTargetArray.type)
}
inline std::string* PTargetArray::unsafe_arena_release_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PTargetArray.type)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return type_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PTargetArray::unsafe_arena_set_allocated_type(
    std::string* type) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (type != nullptr) {
    
  } else {
    
  }
  type_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      type, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PTargetArray.type)
}

// .PCoordinate latest_position = 3;
inline bool PTargetArray::_internal_has_latest_position() const {
  return this != internal_default_instance() && latest_position_ != nullptr;
}
inline bool PTargetArray::has_latest_position() const {
  return _internal_has_latest_position();
}
inline void PTargetArray::clear_latest_position() {
  if (GetArena() == nullptr && latest_position_ != nullptr) {
    delete latest_position_;
  }
  latest_position_ = nullptr;
}
inline const ::PCoordinate& PTargetArray::_internal_latest_position() const {
  const ::PCoordinate* p = latest_position_;
  return p != nullptr ? *p : *reinterpret_cast<const ::PCoordinate*>(
      &::_PCoordinate_default_instance_);
}
inline const ::PCoordinate& PTargetArray::latest_position() const {
  // @@protoc_insertion_point(field_get:PTargetArray.latest_position)
  return _internal_latest_position();
}
inline void PTargetArray::unsafe_arena_set_allocated_latest_position(
    ::PCoordinate* latest_position) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(latest_position_);
  }
  latest_position_ = latest_position;
  if (latest_position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PTargetArray.latest_position)
}
inline ::PCoordinate* PTargetArray::release_latest_position() {
  auto temp = unsafe_arena_release_latest_position();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::PCoordinate* PTargetArray::unsafe_arena_release_latest_position() {
  // @@protoc_insertion_point(field_release:PTargetArray.latest_position)
  
  ::PCoordinate* temp = latest_position_;
  latest_position_ = nullptr;
  return temp;
}
inline ::PCoordinate* PTargetArray::_internal_mutable_latest_position() {
  
  if (latest_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::PCoordinate>(GetArena());
    latest_position_ = p;
  }
  return latest_position_;
}
inline ::PCoordinate* PTargetArray::mutable_latest_position() {
  // @@protoc_insertion_point(field_mutable:PTargetArray.latest_position)
  return _internal_mutable_latest_position();
}
inline void PTargetArray::set_allocated_latest_position(::PCoordinate* latest_position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete latest_position_;
  }
  if (latest_position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(latest_position);
    if (message_arena != submessage_arena) {
      latest_position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, latest_position, submessage_arena);
    }
    
  } else {
    
  }
  latest_position_ = latest_position;
  // @@protoc_insertion_point(field_set_allocated:PTargetArray.latest_position)
}

// int64 update_time = 4;
inline void PTargetArray::clear_update_time() {
  update_time_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PTargetArray::_internal_update_time() const {
  return update_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PTargetArray::update_time() const {
  // @@protoc_insertion_point(field_get:PTargetArray.update_time)
  return _internal_update_time();
}
inline void PTargetArray::_internal_set_update_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  update_time_ = value;
}
inline void PTargetArray::set_update_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_update_time(value);
  // @@protoc_insertion_point(field_set:PTargetArray.update_time)
}

// repeated .PTarget targets = 5;
inline int PTargetArray::_internal_targets_size() const {
  return targets_.size();
}
inline int PTargetArray::targets_size() const {
  return _internal_targets_size();
}
inline void PTargetArray::clear_targets() {
  targets_.Clear();
}
inline ::PTarget* PTargetArray::mutable_targets(int index) {
  // @@protoc_insertion_point(field_mutable:PTargetArray.targets)
  return targets_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PTarget >*
PTargetArray::mutable_targets() {
  // @@protoc_insertion_point(field_mutable_list:PTargetArray.targets)
  return &targets_;
}
inline const ::PTarget& PTargetArray::_internal_targets(int index) const {
  return targets_.Get(index);
}
inline const ::PTarget& PTargetArray::targets(int index) const {
  // @@protoc_insertion_point(field_get:PTargetArray.targets)
  return _internal_targets(index);
}
inline ::PTarget* PTargetArray::_internal_add_targets() {
  return targets_.Add();
}
inline ::PTarget* PTargetArray::add_targets() {
  // @@protoc_insertion_point(field_add:PTargetArray.targets)
  return _internal_add_targets();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PTarget >&
PTargetArray::targets() const {
  // @@protoc_insertion_point(field_list:PTargetArray.targets)
  return targets_;
}

// -------------------------------------------------------------------

// PIndexPoint

// string uuid = 1;
inline void PIndexPoint::clear_uuid() {
  uuid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PIndexPoint::uuid() const {
  // @@protoc_insertion_point(field_get:PIndexPoint.uuid)
  return _internal_uuid();
}
inline void PIndexPoint::set_uuid(const std::string& value) {
  _internal_set_uuid(value);
  // @@protoc_insertion_point(field_set:PIndexPoint.uuid)
}
inline std::string* PIndexPoint::mutable_uuid() {
  // @@protoc_insertion_point(field_mutable:PIndexPoint.uuid)
  return _internal_mutable_uuid();
}
inline const std::string& PIndexPoint::_internal_uuid() const {
  return uuid_.Get();
}
inline void PIndexPoint::_internal_set_uuid(const std::string& value) {
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PIndexPoint::set_uuid(std::string&& value) {
  
  uuid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PIndexPoint.uuid)
}
inline void PIndexPoint::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PIndexPoint.uuid)
}
inline void PIndexPoint::set_uuid(const char* value,
    size_t size) {
  
  uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PIndexPoint.uuid)
}
inline std::string* PIndexPoint::_internal_mutable_uuid() {
  
  return uuid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PIndexPoint::release_uuid() {
  // @@protoc_insertion_point(field_release:PIndexPoint.uuid)
  return uuid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PIndexPoint::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  uuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uuid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PIndexPoint.uuid)
}
inline std::string* PIndexPoint::unsafe_arena_release_uuid() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PIndexPoint.uuid)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return uuid_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PIndexPoint::unsafe_arena_set_allocated_uuid(
    std::string* uuid) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (uuid != nullptr) {
    
  } else {
    
  }
  uuid_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      uuid, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PIndexPoint.uuid)
}

// float x = 2;
inline void PIndexPoint::clear_x() {
  x_ = 0;
}
inline float PIndexPoint::_internal_x() const {
  return x_;
}
inline float PIndexPoint::x() const {
  // @@protoc_insertion_point(field_get:PIndexPoint.x)
  return _internal_x();
}
inline void PIndexPoint::_internal_set_x(float value) {
  
  x_ = value;
}
inline void PIndexPoint::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:PIndexPoint.x)
}

// float y = 3;
inline void PIndexPoint::clear_y() {
  y_ = 0;
}
inline float PIndexPoint::_internal_y() const {
  return y_;
}
inline float PIndexPoint::y() const {
  // @@protoc_insertion_point(field_get:PIndexPoint.y)
  return _internal_y();
}
inline void PIndexPoint::_internal_set_y(float value) {
  
  y_ = value;
}
inline void PIndexPoint::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:PIndexPoint.y)
}

// float z = 4;
inline void PIndexPoint::clear_z() {
  z_ = 0;
}
inline float PIndexPoint::_internal_z() const {
  return z_;
}
inline float PIndexPoint::z() const {
  // @@protoc_insertion_point(field_get:PIndexPoint.z)
  return _internal_z();
}
inline void PIndexPoint::_internal_set_z(float value) {
  
  z_ = value;
}
inline void PIndexPoint::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:PIndexPoint.z)
}

// -------------------------------------------------------------------

// PIndexPointArray

// repeated .PIndexPoint points = 1;
inline int PIndexPointArray::_internal_points_size() const {
  return points_.size();
}
inline int PIndexPointArray::points_size() const {
  return _internal_points_size();
}
inline void PIndexPointArray::clear_points() {
  points_.Clear();
}
inline ::PIndexPoint* PIndexPointArray::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:PIndexPointArray.points)
  return points_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PIndexPoint >*
PIndexPointArray::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:PIndexPointArray.points)
  return &points_;
}
inline const ::PIndexPoint& PIndexPointArray::_internal_points(int index) const {
  return points_.Get(index);
}
inline const ::PIndexPoint& PIndexPointArray::points(int index) const {
  // @@protoc_insertion_point(field_get:PIndexPointArray.points)
  return _internal_points(index);
}
inline ::PIndexPoint* PIndexPointArray::_internal_add_points() {
  return points_.Add();
}
inline ::PIndexPoint* PIndexPointArray::add_points() {
  // @@protoc_insertion_point(field_add:PIndexPointArray.points)
  return _internal_add_points();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PIndexPoint >&
PIndexPointArray::points() const {
  // @@protoc_insertion_point(field_list:PIndexPointArray.points)
  return points_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PTarget_2eproto
