// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PTarget.proto
// Protobuf C++ Version: 4.25.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_PTarget_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_PTarget_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_PTarget_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_PTarget_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_PTarget_2eproto;
class PCoordinate;
struct PCoordinateDefaultTypeInternal;
extern PCoordinateDefaultTypeInternal _PCoordinate_default_instance_;
class PIndexPoint;
struct PIndexPointDefaultTypeInternal;
extern PIndexPointDefaultTypeInternal _PIndexPoint_default_instance_;
class PIndexPointArray;
struct PIndexPointArrayDefaultTypeInternal;
extern PIndexPointArrayDefaultTypeInternal _PIndexPointArray_default_instance_;
class PMat;
struct PMatDefaultTypeInternal;
extern PMatDefaultTypeInternal _PMat_default_instance_;
class PTarget;
struct PTargetDefaultTypeInternal;
extern PTargetDefaultTypeInternal _PTarget_default_instance_;
class PTargetArray;
struct PTargetArrayDefaultTypeInternal;
extern PTargetArrayDefaultTypeInternal _PTargetArray_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class PMat final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PMat) */ {
 public:
  inline PMat() : PMat(nullptr) {}
  ~PMat() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PMat(::google::protobuf::internal::ConstantInitialized);

  inline PMat(const PMat& from)
      : PMat(nullptr, from) {}
  PMat(PMat&& from) noexcept
    : PMat() {
    *this = ::std::move(from);
  }

  inline PMat& operator=(const PMat& from) {
    CopyFrom(from);
    return *this;
  }
  inline PMat& operator=(PMat&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PMat& default_instance() {
    return *internal_default_instance();
  }
  static inline const PMat* internal_default_instance() {
    return reinterpret_cast<const PMat*>(
               &_PMat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PMat& a, PMat& b) {
    a.Swap(&b);
  }
  inline void Swap(PMat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PMat* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PMat* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PMat>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PMat& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const PMat& from) {
    PMat::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PMat* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "PMat";
  }
  protected:
  explicit PMat(::google::protobuf::Arena* arena);
  PMat(::google::protobuf::Arena* arena, const PMat& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
    kSizeFieldNumber = 2,
    kColsFieldNumber = 3,
    kRowsFieldNumber = 4,
  };
  // bytes data = 1;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // int64 size = 2;
  void clear_size() ;
  ::int64_t size() const;
  void set_size(::int64_t value);

  private:
  ::int64_t _internal_size() const;
  void _internal_set_size(::int64_t value);

  public:
  // int32 cols = 3;
  void clear_cols() ;
  ::int32_t cols() const;
  void set_cols(::int32_t value);

  private:
  ::int32_t _internal_cols() const;
  void _internal_set_cols(::int32_t value);

  public:
  // int32 rows = 4;
  void clear_rows() ;
  ::int32_t rows() const;
  void set_rows(::int32_t value);

  private:
  ::int32_t _internal_rows() const;
  void _internal_set_rows(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PMat)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::int64_t size_;
    ::int32_t cols_;
    ::int32_t rows_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PTarget_2eproto;
};// -------------------------------------------------------------------

class PIndexPoint final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PIndexPoint) */ {
 public:
  inline PIndexPoint() : PIndexPoint(nullptr) {}
  ~PIndexPoint() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PIndexPoint(::google::protobuf::internal::ConstantInitialized);

  inline PIndexPoint(const PIndexPoint& from)
      : PIndexPoint(nullptr, from) {}
  PIndexPoint(PIndexPoint&& from) noexcept
    : PIndexPoint() {
    *this = ::std::move(from);
  }

  inline PIndexPoint& operator=(const PIndexPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline PIndexPoint& operator=(PIndexPoint&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PIndexPoint& default_instance() {
    return *internal_default_instance();
  }
  static inline const PIndexPoint* internal_default_instance() {
    return reinterpret_cast<const PIndexPoint*>(
               &_PIndexPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PIndexPoint& a, PIndexPoint& b) {
    a.Swap(&b);
  }
  inline void Swap(PIndexPoint* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PIndexPoint* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PIndexPoint* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PIndexPoint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PIndexPoint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const PIndexPoint& from) {
    PIndexPoint::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PIndexPoint* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "PIndexPoint";
  }
  protected:
  explicit PIndexPoint(::google::protobuf::Arena* arena);
  PIndexPoint(::google::protobuf::Arena* arena, const PIndexPoint& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUuidFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kZFieldNumber = 4,
  };
  // string uuid = 1;
  void clear_uuid() ;
  const std::string& uuid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* value);

  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(
      const std::string& value);
  std::string* _internal_mutable_uuid();

  public:
  // float x = 2;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 3;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 4;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:PIndexPoint)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      24, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    float x_;
    float y_;
    float z_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PTarget_2eproto;
};// -------------------------------------------------------------------

class PCoordinate final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PCoordinate) */ {
 public:
  inline PCoordinate() : PCoordinate(nullptr) {}
  ~PCoordinate() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PCoordinate(::google::protobuf::internal::ConstantInitialized);

  inline PCoordinate(const PCoordinate& from)
      : PCoordinate(nullptr, from) {}
  PCoordinate(PCoordinate&& from) noexcept
    : PCoordinate() {
    *this = ::std::move(from);
  }

  inline PCoordinate& operator=(const PCoordinate& from) {
    CopyFrom(from);
    return *this;
  }
  inline PCoordinate& operator=(PCoordinate&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PCoordinate& default_instance() {
    return *internal_default_instance();
  }
  static inline const PCoordinate* internal_default_instance() {
    return reinterpret_cast<const PCoordinate*>(
               &_PCoordinate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PCoordinate& a, PCoordinate& b) {
    a.Swap(&b);
  }
  inline void Swap(PCoordinate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PCoordinate* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PCoordinate* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PCoordinate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PCoordinate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const PCoordinate& from) {
    PCoordinate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PCoordinate* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "PCoordinate";
  }
  protected:
  explicit PCoordinate(::google::protobuf::Arena* arena);
  PCoordinate(::google::protobuf::Arena* arena, const PCoordinate& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 3;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:PCoordinate)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    float x_;
    float y_;
    float z_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PTarget_2eproto;
};// -------------------------------------------------------------------

class PTarget final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PTarget) */ {
 public:
  inline PTarget() : PTarget(nullptr) {}
  ~PTarget() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PTarget(::google::protobuf::internal::ConstantInitialized);

  inline PTarget(const PTarget& from)
      : PTarget(nullptr, from) {}
  PTarget(PTarget&& from) noexcept
    : PTarget() {
    *this = ::std::move(from);
  }

  inline PTarget& operator=(const PTarget& from) {
    CopyFrom(from);
    return *this;
  }
  inline PTarget& operator=(PTarget&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PTarget& default_instance() {
    return *internal_default_instance();
  }
  static inline const PTarget* internal_default_instance() {
    return reinterpret_cast<const PTarget*>(
               &_PTarget_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PTarget& a, PTarget& b) {
    a.Swap(&b);
  }
  inline void Swap(PTarget* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PTarget* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PTarget* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PTarget>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PTarget& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const PTarget& from) {
    PTarget::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PTarget* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "PTarget";
  }
  protected:
  explicit PTarget(::google::protobuf::Arena* arena);
  PTarget(::google::protobuf::Arena* arena, const PTarget& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUuidFieldNumber = 1,
    kTypeFieldNumber = 2,
    kImageFieldNumber = 3,
    kPositionFieldNumber = 4,
    kTimeStampFieldNumber = 5,
  };
  // string uuid = 1;
  void clear_uuid() ;
  const std::string& uuid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* value);

  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(
      const std::string& value);
  std::string* _internal_mutable_uuid();

  public:
  // string type = 2;
  void clear_type() ;
  const std::string& type() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* value);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // .PMat image = 3;
  bool has_image() const;
  void clear_image() ;
  const ::PMat& image() const;
  PROTOBUF_NODISCARD ::PMat* release_image();
  ::PMat* mutable_image();
  void set_allocated_image(::PMat* value);
  void unsafe_arena_set_allocated_image(::PMat* value);
  ::PMat* unsafe_arena_release_image();

  private:
  const ::PMat& _internal_image() const;
  ::PMat* _internal_mutable_image();

  public:
  // .PCoordinate position = 4;
  bool has_position() const;
  void clear_position() ;
  const ::PCoordinate& position() const;
  PROTOBUF_NODISCARD ::PCoordinate* release_position();
  ::PCoordinate* mutable_position();
  void set_allocated_position(::PCoordinate* value);
  void unsafe_arena_set_allocated_position(::PCoordinate* value);
  ::PCoordinate* unsafe_arena_release_position();

  private:
  const ::PCoordinate& _internal_position() const;
  ::PCoordinate* _internal_mutable_position();

  public:
  // int64 time_stamp = 5;
  void clear_time_stamp() ;
  ::int64_t time_stamp() const;
  void set_time_stamp(::int64_t value);

  private:
  ::int64_t _internal_time_stamp() const;
  void _internal_set_time_stamp(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:PTarget)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 2,
      24, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    ::google::protobuf::internal::ArenaStringPtr type_;
    ::PMat* image_;
    ::PCoordinate* position_;
    ::int64_t time_stamp_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PTarget_2eproto;
};// -------------------------------------------------------------------

class PIndexPointArray final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PIndexPointArray) */ {
 public:
  inline PIndexPointArray() : PIndexPointArray(nullptr) {}
  ~PIndexPointArray() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PIndexPointArray(::google::protobuf::internal::ConstantInitialized);

  inline PIndexPointArray(const PIndexPointArray& from)
      : PIndexPointArray(nullptr, from) {}
  PIndexPointArray(PIndexPointArray&& from) noexcept
    : PIndexPointArray() {
    *this = ::std::move(from);
  }

  inline PIndexPointArray& operator=(const PIndexPointArray& from) {
    CopyFrom(from);
    return *this;
  }
  inline PIndexPointArray& operator=(PIndexPointArray&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PIndexPointArray& default_instance() {
    return *internal_default_instance();
  }
  static inline const PIndexPointArray* internal_default_instance() {
    return reinterpret_cast<const PIndexPointArray*>(
               &_PIndexPointArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(PIndexPointArray& a, PIndexPointArray& b) {
    a.Swap(&b);
  }
  inline void Swap(PIndexPointArray* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PIndexPointArray* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PIndexPointArray* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PIndexPointArray>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PIndexPointArray& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const PIndexPointArray& from) {
    PIndexPointArray::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PIndexPointArray* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "PIndexPointArray";
  }
  protected:
  explicit PIndexPointArray(::google::protobuf::Arena* arena);
  PIndexPointArray(::google::protobuf::Arena* arena, const PIndexPointArray& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointsFieldNumber = 1,
  };
  // repeated .PIndexPoint points = 1;
  int points_size() const;
  private:
  int _internal_points_size() const;

  public:
  void clear_points() ;
  ::PIndexPoint* mutable_points(int index);
  ::google::protobuf::RepeatedPtrField< ::PIndexPoint >*
      mutable_points();
  private:
  const ::google::protobuf::RepeatedPtrField<::PIndexPoint>& _internal_points() const;
  ::google::protobuf::RepeatedPtrField<::PIndexPoint>* _internal_mutable_points();
  public:
  const ::PIndexPoint& points(int index) const;
  ::PIndexPoint* add_points();
  const ::google::protobuf::RepeatedPtrField< ::PIndexPoint >&
      points() const;
  // @@protoc_insertion_point(class_scope:PIndexPointArray)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::PIndexPoint > points_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PTarget_2eproto;
};// -------------------------------------------------------------------

class PTargetArray final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PTargetArray) */ {
 public:
  inline PTargetArray() : PTargetArray(nullptr) {}
  ~PTargetArray() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PTargetArray(::google::protobuf::internal::ConstantInitialized);

  inline PTargetArray(const PTargetArray& from)
      : PTargetArray(nullptr, from) {}
  PTargetArray(PTargetArray&& from) noexcept
    : PTargetArray() {
    *this = ::std::move(from);
  }

  inline PTargetArray& operator=(const PTargetArray& from) {
    CopyFrom(from);
    return *this;
  }
  inline PTargetArray& operator=(PTargetArray&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PTargetArray& default_instance() {
    return *internal_default_instance();
  }
  static inline const PTargetArray* internal_default_instance() {
    return reinterpret_cast<const PTargetArray*>(
               &_PTargetArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PTargetArray& a, PTargetArray& b) {
    a.Swap(&b);
  }
  inline void Swap(PTargetArray* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PTargetArray* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PTargetArray* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PTargetArray>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PTargetArray& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const PTargetArray& from) {
    PTargetArray::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PTargetArray* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "PTargetArray";
  }
  protected:
  explicit PTargetArray(::google::protobuf::Arena* arena);
  PTargetArray(::google::protobuf::Arena* arena, const PTargetArray& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetsFieldNumber = 5,
    kUuidFieldNumber = 1,
    kTypeFieldNumber = 2,
    kLatestPositionFieldNumber = 3,
    kUpdateTimeFieldNumber = 4,
  };
  // repeated .PTarget targets = 5;
  int targets_size() const;
  private:
  int _internal_targets_size() const;

  public:
  void clear_targets() ;
  ::PTarget* mutable_targets(int index);
  ::google::protobuf::RepeatedPtrField< ::PTarget >*
      mutable_targets();
  private:
  const ::google::protobuf::RepeatedPtrField<::PTarget>& _internal_targets() const;
  ::google::protobuf::RepeatedPtrField<::PTarget>* _internal_mutable_targets();
  public:
  const ::PTarget& targets(int index) const;
  ::PTarget* add_targets();
  const ::google::protobuf::RepeatedPtrField< ::PTarget >&
      targets() const;
  // string uuid = 1;
  void clear_uuid() ;
  const std::string& uuid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* value);

  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(
      const std::string& value);
  std::string* _internal_mutable_uuid();

  public:
  // string type = 2;
  void clear_type() ;
  const std::string& type() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* value);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // .PCoordinate latest_position = 3;
  bool has_latest_position() const;
  void clear_latest_position() ;
  const ::PCoordinate& latest_position() const;
  PROTOBUF_NODISCARD ::PCoordinate* release_latest_position();
  ::PCoordinate* mutable_latest_position();
  void set_allocated_latest_position(::PCoordinate* value);
  void unsafe_arena_set_allocated_latest_position(::PCoordinate* value);
  ::PCoordinate* unsafe_arena_release_latest_position();

  private:
  const ::PCoordinate& _internal_latest_position() const;
  ::PCoordinate* _internal_mutable_latest_position();

  public:
  // int64 update_time = 4;
  void clear_update_time() ;
  ::int64_t update_time() const;
  void set_update_time(::int64_t value);

  private:
  ::int64_t _internal_update_time() const;
  void _internal_set_update_time(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:PTargetArray)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 2,
      29, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::PTarget > targets_;
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    ::google::protobuf::internal::ArenaStringPtr type_;
    ::PCoordinate* latest_position_;
    ::int64_t update_time_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PTarget_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PMat

// bytes data = 1;
inline void PMat::clear_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& PMat::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PMat.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PMat::set_data(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PMat.data)
}
inline std::string* PMat::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:PMat.data)
  return _s;
}
inline const std::string& PMat::_internal_data() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.data_.Get();
}
inline void PMat::_internal_set_data(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.data_.Set(value, GetArena());
}
inline std::string* PMat::_internal_mutable_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* PMat::release_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:PMat.data)
  return _impl_.data_.Release();
}
inline void PMat::set_allocated_data(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.data_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.data_.IsDefault()) {
          _impl_.data_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PMat.data)
}

// int64 size = 2;
inline void PMat::clear_size() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.size_ = ::int64_t{0};
}
inline ::int64_t PMat::size() const {
  // @@protoc_insertion_point(field_get:PMat.size)
  return _internal_size();
}
inline void PMat::set_size(::int64_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:PMat.size)
}
inline ::int64_t PMat::_internal_size() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.size_;
}
inline void PMat::_internal_set_size(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.size_ = value;
}

// int32 cols = 3;
inline void PMat::clear_cols() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.cols_ = 0;
}
inline ::int32_t PMat::cols() const {
  // @@protoc_insertion_point(field_get:PMat.cols)
  return _internal_cols();
}
inline void PMat::set_cols(::int32_t value) {
  _internal_set_cols(value);
  // @@protoc_insertion_point(field_set:PMat.cols)
}
inline ::int32_t PMat::_internal_cols() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.cols_;
}
inline void PMat::_internal_set_cols(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.cols_ = value;
}

// int32 rows = 4;
inline void PMat::clear_rows() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.rows_ = 0;
}
inline ::int32_t PMat::rows() const {
  // @@protoc_insertion_point(field_get:PMat.rows)
  return _internal_rows();
}
inline void PMat::set_rows(::int32_t value) {
  _internal_set_rows(value);
  // @@protoc_insertion_point(field_set:PMat.rows)
}
inline ::int32_t PMat::_internal_rows() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.rows_;
}
inline void PMat::_internal_set_rows(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.rows_ = value;
}

// -------------------------------------------------------------------

// PCoordinate

// float x = 1;
inline void PCoordinate::clear_x() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.x_ = 0;
}
inline float PCoordinate::x() const {
  // @@protoc_insertion_point(field_get:PCoordinate.x)
  return _internal_x();
}
inline void PCoordinate::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:PCoordinate.x)
}
inline float PCoordinate::_internal_x() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.x_;
}
inline void PCoordinate::_internal_set_x(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.x_ = value;
}

// float y = 2;
inline void PCoordinate::clear_y() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.y_ = 0;
}
inline float PCoordinate::y() const {
  // @@protoc_insertion_point(field_get:PCoordinate.y)
  return _internal_y();
}
inline void PCoordinate::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:PCoordinate.y)
}
inline float PCoordinate::_internal_y() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.y_;
}
inline void PCoordinate::_internal_set_y(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.y_ = value;
}

// float z = 3;
inline void PCoordinate::clear_z() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.z_ = 0;
}
inline float PCoordinate::z() const {
  // @@protoc_insertion_point(field_get:PCoordinate.z)
  return _internal_z();
}
inline void PCoordinate::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:PCoordinate.z)
}
inline float PCoordinate::_internal_z() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.z_;
}
inline void PCoordinate::_internal_set_z(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// PTarget

// string uuid = 1;
inline void PTarget::clear_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& PTarget::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PTarget.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PTarget::set_uuid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PTarget.uuid)
}
inline std::string* PTarget::mutable_uuid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:PTarget.uuid)
  return _s;
}
inline const std::string& PTarget::_internal_uuid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.uuid_.Get();
}
inline void PTarget::_internal_set_uuid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.uuid_.Set(value, GetArena());
}
inline std::string* PTarget::_internal_mutable_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.uuid_.Mutable( GetArena());
}
inline std::string* PTarget::release_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:PTarget.uuid)
  return _impl_.uuid_.Release();
}
inline void PTarget::set_allocated_uuid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.uuid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.uuid_.IsDefault()) {
          _impl_.uuid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PTarget.uuid)
}

// string type = 2;
inline void PTarget::clear_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.type_.ClearToEmpty();
}
inline const std::string& PTarget::type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PTarget.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PTarget::set_type(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PTarget.type)
}
inline std::string* PTarget::mutable_type() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:PTarget.type)
  return _s;
}
inline const std::string& PTarget::_internal_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.type_.Get();
}
inline void PTarget::_internal_set_type(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.type_.Set(value, GetArena());
}
inline std::string* PTarget::_internal_mutable_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.type_.Mutable( GetArena());
}
inline std::string* PTarget::release_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:PTarget.type)
  return _impl_.type_.Release();
}
inline void PTarget::set_allocated_type(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.type_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.type_.IsDefault()) {
          _impl_.type_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PTarget.type)
}

// .PMat image = 3;
inline bool PTarget::has_image() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.image_ != nullptr);
  return value;
}
inline void PTarget::clear_image() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.image_ != nullptr) _impl_.image_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::PMat& PTarget::_internal_image() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::PMat* p = _impl_.image_;
  return p != nullptr ? *p : reinterpret_cast<const ::PMat&>(::_PMat_default_instance_);
}
inline const ::PMat& PTarget::image() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PTarget.image)
  return _internal_image();
}
inline void PTarget::unsafe_arena_set_allocated_image(::PMat* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.image_);
  }
  _impl_.image_ = reinterpret_cast<::PMat*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PTarget.image)
}
inline ::PMat* PTarget::release_image() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PMat* released = _impl_.image_;
  _impl_.image_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::PMat* PTarget::unsafe_arena_release_image() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:PTarget.image)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PMat* temp = _impl_.image_;
  _impl_.image_ = nullptr;
  return temp;
}
inline ::PMat* PTarget::_internal_mutable_image() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.image_ == nullptr) {
    auto* p = CreateMaybeMessage<::PMat>(GetArena());
    _impl_.image_ = reinterpret_cast<::PMat*>(p);
  }
  return _impl_.image_;
}
inline ::PMat* PTarget::mutable_image() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::PMat* _msg = _internal_mutable_image();
  // @@protoc_insertion_point(field_mutable:PTarget.image)
  return _msg;
}
inline void PTarget::set_allocated_image(::PMat* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::PMat*>(_impl_.image_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::PMat*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.image_ = reinterpret_cast<::PMat*>(value);
  // @@protoc_insertion_point(field_set_allocated:PTarget.image)
}

// .PCoordinate position = 4;
inline bool PTarget::has_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.position_ != nullptr);
  return value;
}
inline void PTarget::clear_position() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.position_ != nullptr) _impl_.position_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::PCoordinate& PTarget::_internal_position() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::PCoordinate* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::PCoordinate&>(::_PCoordinate_default_instance_);
}
inline const ::PCoordinate& PTarget::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PTarget.position)
  return _internal_position();
}
inline void PTarget::unsafe_arena_set_allocated_position(::PCoordinate* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = reinterpret_cast<::PCoordinate*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PTarget.position)
}
inline ::PCoordinate* PTarget::release_position() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::PCoordinate* released = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::PCoordinate* PTarget::unsafe_arena_release_position() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:PTarget.position)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::PCoordinate* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::PCoordinate* PTarget::_internal_mutable_position() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.position_ == nullptr) {
    auto* p = CreateMaybeMessage<::PCoordinate>(GetArena());
    _impl_.position_ = reinterpret_cast<::PCoordinate*>(p);
  }
  return _impl_.position_;
}
inline ::PCoordinate* PTarget::mutable_position() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::PCoordinate* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:PTarget.position)
  return _msg;
}
inline void PTarget::set_allocated_position(::PCoordinate* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::PCoordinate*>(_impl_.position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::PCoordinate*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.position_ = reinterpret_cast<::PCoordinate*>(value);
  // @@protoc_insertion_point(field_set_allocated:PTarget.position)
}

// int64 time_stamp = 5;
inline void PTarget::clear_time_stamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.time_stamp_ = ::int64_t{0};
}
inline ::int64_t PTarget::time_stamp() const {
  // @@protoc_insertion_point(field_get:PTarget.time_stamp)
  return _internal_time_stamp();
}
inline void PTarget::set_time_stamp(::int64_t value) {
  _internal_set_time_stamp(value);
  // @@protoc_insertion_point(field_set:PTarget.time_stamp)
}
inline ::int64_t PTarget::_internal_time_stamp() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.time_stamp_;
}
inline void PTarget::_internal_set_time_stamp(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.time_stamp_ = value;
}

// -------------------------------------------------------------------

// PTargetArray

// string uuid = 1;
inline void PTargetArray::clear_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& PTargetArray::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PTargetArray.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PTargetArray::set_uuid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PTargetArray.uuid)
}
inline std::string* PTargetArray::mutable_uuid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:PTargetArray.uuid)
  return _s;
}
inline const std::string& PTargetArray::_internal_uuid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.uuid_.Get();
}
inline void PTargetArray::_internal_set_uuid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.uuid_.Set(value, GetArena());
}
inline std::string* PTargetArray::_internal_mutable_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.uuid_.Mutable( GetArena());
}
inline std::string* PTargetArray::release_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:PTargetArray.uuid)
  return _impl_.uuid_.Release();
}
inline void PTargetArray::set_allocated_uuid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.uuid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.uuid_.IsDefault()) {
          _impl_.uuid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PTargetArray.uuid)
}

// string type = 2;
inline void PTargetArray::clear_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.type_.ClearToEmpty();
}
inline const std::string& PTargetArray::type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PTargetArray.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PTargetArray::set_type(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PTargetArray.type)
}
inline std::string* PTargetArray::mutable_type() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:PTargetArray.type)
  return _s;
}
inline const std::string& PTargetArray::_internal_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.type_.Get();
}
inline void PTargetArray::_internal_set_type(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.type_.Set(value, GetArena());
}
inline std::string* PTargetArray::_internal_mutable_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.type_.Mutable( GetArena());
}
inline std::string* PTargetArray::release_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:PTargetArray.type)
  return _impl_.type_.Release();
}
inline void PTargetArray::set_allocated_type(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.type_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.type_.IsDefault()) {
          _impl_.type_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PTargetArray.type)
}

// .PCoordinate latest_position = 3;
inline bool PTargetArray::has_latest_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.latest_position_ != nullptr);
  return value;
}
inline void PTargetArray::clear_latest_position() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.latest_position_ != nullptr) _impl_.latest_position_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::PCoordinate& PTargetArray::_internal_latest_position() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::PCoordinate* p = _impl_.latest_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::PCoordinate&>(::_PCoordinate_default_instance_);
}
inline const ::PCoordinate& PTargetArray::latest_position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PTargetArray.latest_position)
  return _internal_latest_position();
}
inline void PTargetArray::unsafe_arena_set_allocated_latest_position(::PCoordinate* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.latest_position_);
  }
  _impl_.latest_position_ = reinterpret_cast<::PCoordinate*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PTargetArray.latest_position)
}
inline ::PCoordinate* PTargetArray::release_latest_position() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PCoordinate* released = _impl_.latest_position_;
  _impl_.latest_position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::PCoordinate* PTargetArray::unsafe_arena_release_latest_position() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:PTargetArray.latest_position)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::PCoordinate* temp = _impl_.latest_position_;
  _impl_.latest_position_ = nullptr;
  return temp;
}
inline ::PCoordinate* PTargetArray::_internal_mutable_latest_position() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.latest_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::PCoordinate>(GetArena());
    _impl_.latest_position_ = reinterpret_cast<::PCoordinate*>(p);
  }
  return _impl_.latest_position_;
}
inline ::PCoordinate* PTargetArray::mutable_latest_position() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::PCoordinate* _msg = _internal_mutable_latest_position();
  // @@protoc_insertion_point(field_mutable:PTargetArray.latest_position)
  return _msg;
}
inline void PTargetArray::set_allocated_latest_position(::PCoordinate* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::PCoordinate*>(_impl_.latest_position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::PCoordinate*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.latest_position_ = reinterpret_cast<::PCoordinate*>(value);
  // @@protoc_insertion_point(field_set_allocated:PTargetArray.latest_position)
}

// int64 update_time = 4;
inline void PTargetArray::clear_update_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.update_time_ = ::int64_t{0};
}
inline ::int64_t PTargetArray::update_time() const {
  // @@protoc_insertion_point(field_get:PTargetArray.update_time)
  return _internal_update_time();
}
inline void PTargetArray::set_update_time(::int64_t value) {
  _internal_set_update_time(value);
  // @@protoc_insertion_point(field_set:PTargetArray.update_time)
}
inline ::int64_t PTargetArray::_internal_update_time() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.update_time_;
}
inline void PTargetArray::_internal_set_update_time(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.update_time_ = value;
}

// repeated .PTarget targets = 5;
inline int PTargetArray::_internal_targets_size() const {
  return _internal_targets().size();
}
inline int PTargetArray::targets_size() const {
  return _internal_targets_size();
}
inline void PTargetArray::clear_targets() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.targets_.Clear();
}
inline ::PTarget* PTargetArray::mutable_targets(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:PTargetArray.targets)
  return _internal_mutable_targets()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::PTarget>* PTargetArray::mutable_targets()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:PTargetArray.targets)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_targets();
}
inline const ::PTarget& PTargetArray::targets(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PTargetArray.targets)
  return _internal_targets().Get(index);
}
inline ::PTarget* PTargetArray::add_targets() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::PTarget* _add = _internal_mutable_targets()->Add();
  // @@protoc_insertion_point(field_add:PTargetArray.targets)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::PTarget>& PTargetArray::targets() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:PTargetArray.targets)
  return _internal_targets();
}
inline const ::google::protobuf::RepeatedPtrField<::PTarget>&
PTargetArray::_internal_targets() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.targets_;
}
inline ::google::protobuf::RepeatedPtrField<::PTarget>*
PTargetArray::_internal_mutable_targets() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.targets_;
}

// -------------------------------------------------------------------

// PIndexPoint

// string uuid = 1;
inline void PIndexPoint::clear_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& PIndexPoint::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PIndexPoint.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PIndexPoint::set_uuid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PIndexPoint.uuid)
}
inline std::string* PIndexPoint::mutable_uuid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:PIndexPoint.uuid)
  return _s;
}
inline const std::string& PIndexPoint::_internal_uuid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.uuid_.Get();
}
inline void PIndexPoint::_internal_set_uuid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.uuid_.Set(value, GetArena());
}
inline std::string* PIndexPoint::_internal_mutable_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.uuid_.Mutable( GetArena());
}
inline std::string* PIndexPoint::release_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:PIndexPoint.uuid)
  return _impl_.uuid_.Release();
}
inline void PIndexPoint::set_allocated_uuid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.uuid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.uuid_.IsDefault()) {
          _impl_.uuid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PIndexPoint.uuid)
}

// float x = 2;
inline void PIndexPoint::clear_x() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.x_ = 0;
}
inline float PIndexPoint::x() const {
  // @@protoc_insertion_point(field_get:PIndexPoint.x)
  return _internal_x();
}
inline void PIndexPoint::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:PIndexPoint.x)
}
inline float PIndexPoint::_internal_x() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.x_;
}
inline void PIndexPoint::_internal_set_x(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.x_ = value;
}

// float y = 3;
inline void PIndexPoint::clear_y() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.y_ = 0;
}
inline float PIndexPoint::y() const {
  // @@protoc_insertion_point(field_get:PIndexPoint.y)
  return _internal_y();
}
inline void PIndexPoint::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:PIndexPoint.y)
}
inline float PIndexPoint::_internal_y() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.y_;
}
inline void PIndexPoint::_internal_set_y(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.y_ = value;
}

// float z = 4;
inline void PIndexPoint::clear_z() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.z_ = 0;
}
inline float PIndexPoint::z() const {
  // @@protoc_insertion_point(field_get:PIndexPoint.z)
  return _internal_z();
}
inline void PIndexPoint::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:PIndexPoint.z)
}
inline float PIndexPoint::_internal_z() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.z_;
}
inline void PIndexPoint::_internal_set_z(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// PIndexPointArray

// repeated .PIndexPoint points = 1;
inline int PIndexPointArray::_internal_points_size() const {
  return _internal_points().size();
}
inline int PIndexPointArray::points_size() const {
  return _internal_points_size();
}
inline void PIndexPointArray::clear_points() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.points_.Clear();
}
inline ::PIndexPoint* PIndexPointArray::mutable_points(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:PIndexPointArray.points)
  return _internal_mutable_points()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::PIndexPoint>* PIndexPointArray::mutable_points()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:PIndexPointArray.points)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_points();
}
inline const ::PIndexPoint& PIndexPointArray::points(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PIndexPointArray.points)
  return _internal_points().Get(index);
}
inline ::PIndexPoint* PIndexPointArray::add_points() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::PIndexPoint* _add = _internal_mutable_points()->Add();
  // @@protoc_insertion_point(field_add:PIndexPointArray.points)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::PIndexPoint>& PIndexPointArray::points() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:PIndexPointArray.points)
  return _internal_points();
}
inline const ::google::protobuf::RepeatedPtrField<::PIndexPoint>&
PIndexPointArray::_internal_points() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.points_;
}
inline ::google::protobuf::RepeatedPtrField<::PIndexPoint>*
PIndexPointArray::_internal_mutable_points() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.points_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_PTarget_2eproto_2epb_2eh
